logger:
  active: true             # Enable or disable logging (true | false)
  level: "info"            # Minimum log level: debug | info | warn | error
  encoding: "console"      # Log output format: console (human-readable) | json
  mode: "stdout"           # Log destination: stdout | file

  file:                    # File logging settings (used only if mode = "file")
    path: ""               # Path to the log file
    maxSize:               # Maximum file size (in MB) before rotation
    maxBackups:            # Number of rotated log files to keep
    maxAge:                # Maximum age (in days) to retain old log files
    compress:              # Compress old log files on rotation (true | false)

dht:
  idBits:                # Identifier space size (keyspace = 2^idBits)
  mode: ""          # Network mode: public (real network) | private (local/isolated)

  bootstrap:
    mode: ""              # Bootstrap mode: static | route53
    peers: []                   # List of peer addresses (used if mode = "static")

    route53:
      hostedZoneId: ""          # AWS Route53 hosted zone ID
      domainSuffix: ""          # Domain suffix for SRV records (e.g., "koorde.dht")
      ttl:                      # TTL for SRV records (in seconds)
      region: ""                # AWS region for Route53 queries (e.g., "us-east-1")

  deBruijn:
    degree:                     # Degree of the de Bruijn graph (2 = minimal, log n = optimal; must be a power of 2 for binary IDs)
    fixInterval:             # Periodic refresh interval for de Bruijn pointers

  storage:
    fixInterval:            # Periodic refresh interval for key-value storage maintenance

  faultTolerance:
    successorListSize:          # Number of successors to maintain (≈ log n for fault tolerance)
    stabilizationInterval:     # Periodic interval for successor stabilization
    failureTimeout:            # Timeout for gRPC stabilization calls; nodes exceeding this timeout are marked as failed

node:
  id: ""                        # Node identifier in hexadecimal (empty = randomly generated)
  bind: ""                      # Local bind address for the gRPC server (empty = all interfaces)
  host: ""                      # Publicly advertised host (empty = same as bind)
  port: 0                       # gRPC server port (0 = automatically choose a free port)

telemetry:
  tracing:
    enabled: false               # Enable or disable distributed tracing (true | false)
    exporter:                    # Tracing exporter: otlp | jaeger
    endpoint:                    # Exporter endpoint (OTLP or Jaeger collector address)
