// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: dht/v1/node.proto

package dhtv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // Node identifier (big-endian hash)
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // Network address (IP:Port)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_dht_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Node) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type FindSuccessorRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TargetId []byte                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // ID to resolve
	// Types that are valid to be assigned to Mode:
	//
	//	*FindSuccessorRequest_Initial
	//	*FindSuccessorRequest_Step
	Mode          isFindSuccessorRequest_Mode `protobuf_oneof:"mode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorRequest) Reset() {
	*x = FindSuccessorRequest{}
	mi := &file_dht_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorRequest) ProtoMessage() {}

func (x *FindSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorRequest.ProtoReflect.Descriptor instead.
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *FindSuccessorRequest) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *FindSuccessorRequest) GetMode() isFindSuccessorRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *FindSuccessorRequest) GetInitial() *Initial {
	if x != nil {
		if x, ok := x.Mode.(*FindSuccessorRequest_Initial); ok {
			return x.Initial
		}
	}
	return nil
}

func (x *FindSuccessorRequest) GetStep() *Step {
	if x != nil {
		if x, ok := x.Mode.(*FindSuccessorRequest_Step); ok {
			return x.Step
		}
	}
	return nil
}

type isFindSuccessorRequest_Mode interface {
	isFindSuccessorRequest_Mode()
}

type FindSuccessorRequest_Initial struct {
	Initial *Initial `protobuf:"bytes,2,opt,name=initial,proto3,oneof"` // first step
}

type FindSuccessorRequest_Step struct {
	Step *Step `protobuf:"bytes,3,opt,name=step,proto3,oneof"` // subsequent steps
}

func (*FindSuccessorRequest_Initial) isFindSuccessorRequest_Mode() {}

func (*FindSuccessorRequest_Step) isFindSuccessorRequest_Mode() {}

type Initial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Initial) Reset() {
	*x = Initial{}
	mi := &file_dht_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Initial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initial) ProtoMessage() {}

func (x *Initial) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initial.ProtoReflect.Descriptor instead.
func (*Initial) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{2}
}

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentI      []byte                 `protobuf:"bytes,1,opt,name=current_i,json=currentI,proto3" json:"current_i,omitempty"` // imaginary node
	KShift        []byte                 `protobuf:"bytes,2,opt,name=k_shift,json=kShift,proto3" json:"k_shift,omitempty"`       // key shifted state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_dht_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *Step) GetCurrentI() []byte {
	if x != nil {
		return x.CurrentI
	}
	return nil
}

func (x *Step) GetKShift() []byte {
	if x != nil {
		return x.KShift
	}
	return nil
}

type FindSuccessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"` // successor responsible for target_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorResponse) Reset() {
	*x = FindSuccessorResponse{}
	mi := &file_dht_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorResponse) ProtoMessage() {}

func (x *FindSuccessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorResponse.ProtoReflect.Descriptor instead.
func (*FindSuccessorResponse) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *FindSuccessorResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// Successor list
type SuccessorList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successors    []*Node                `protobuf:"bytes,1,rep,name=successors,proto3" json:"successors,omitempty"` // list of successors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessorList) Reset() {
	*x = SuccessorList{}
	mi := &file_dht_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessorList) ProtoMessage() {}

func (x *SuccessorList) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessorList.ProtoReflect.Descriptor instead.
func (*SuccessorList) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *SuccessorList) GetSuccessors() []*Node {
	if x != nil {
		return x.Successors
	}
	return nil
}

// Store a resource (Put).
type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_dht_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *StoreRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StoreRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Retrieve a resource (Get).
type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_dht_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *RetrieveRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_dht_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *RetrieveResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Remove a resource (Delete).
type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_dht_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dht_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_dht_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_dht_v1_node_proto protoreflect.FileDescriptor

const file_dht_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x11dht/v1/node.proto\x12\x06dht.v1\x1a\x1bgoogle/protobuf/empty.proto\"0\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x8c\x01\n" +
	"\x14FindSuccessorRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\fR\btargetId\x12+\n" +
	"\ainitial\x18\x02 \x01(\v2\x0f.dht.v1.InitialH\x00R\ainitial\x12\"\n" +
	"\x04step\x18\x03 \x01(\v2\f.dht.v1.StepH\x00R\x04stepB\x06\n" +
	"\x04mode\"\t\n" +
	"\aInitial\"<\n" +
	"\x04Step\x12\x1b\n" +
	"\tcurrent_i\x18\x01 \x01(\fR\bcurrentI\x12\x17\n" +
	"\ak_shift\x18\x02 \x01(\fR\x06kShift\"9\n" +
	"\x15FindSuccessorResponse\x12 \n" +
	"\x04node\x18\x01 \x01(\v2\f.dht.v1.NodeR\x04node\"=\n" +
	"\rSuccessorList\x12,\n" +
	"\n" +
	"successors\x18\x01 \x03(\v2\f.dht.v1.NodeR\n" +
	"successors\"6\n" +
	"\fStoreRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"#\n" +
	"\x0fRetrieveRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"(\n" +
	"\x10RetrieveResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\rRemoveRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key2\xe5\x03\n" +
	"\x03DHT\x12L\n" +
	"\rFindSuccessor\x12\x1c.dht.v1.FindSuccessorRequest\x1a\x1d.dht.v1.FindSuccessorResponse\x126\n" +
	"\x0eGetPredecessor\x12\x16.google.protobuf.Empty\x1a\f.dht.v1.Node\x12A\n" +
	"\x10GetSuccessorList\x12\x16.google.protobuf.Empty\x1a\x15.dht.v1.SuccessorList\x12.\n" +
	"\x06Notify\x12\f.dht.v1.Node\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x125\n" +
	"\x05Store\x12\x14.dht.v1.StoreRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\bRetrieve\x12\x17.dht.v1.RetrieveRequest\x1a\x18.dht.v1.RetrieveResponse\x127\n" +
	"\x06Remove\x12\x15.dht.v1.RemoveRequest\x1a\x16.google.protobuf.EmptyB@Z>github.com/flaviosimonelli/KoordeDHT/internal/api/dht/v1;dhtv1b\x06proto3"

var (
	file_dht_v1_node_proto_rawDescOnce sync.Once
	file_dht_v1_node_proto_rawDescData []byte
)

func file_dht_v1_node_proto_rawDescGZIP() []byte {
	file_dht_v1_node_proto_rawDescOnce.Do(func() {
		file_dht_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dht_v1_node_proto_rawDesc), len(file_dht_v1_node_proto_rawDesc)))
	})
	return file_dht_v1_node_proto_rawDescData
}

var file_dht_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dht_v1_node_proto_goTypes = []any{
	(*Node)(nil),                  // 0: dht.v1.Node
	(*FindSuccessorRequest)(nil),  // 1: dht.v1.FindSuccessorRequest
	(*Initial)(nil),               // 2: dht.v1.Initial
	(*Step)(nil),                  // 3: dht.v1.Step
	(*FindSuccessorResponse)(nil), // 4: dht.v1.FindSuccessorResponse
	(*SuccessorList)(nil),         // 5: dht.v1.SuccessorList
	(*StoreRequest)(nil),          // 6: dht.v1.StoreRequest
	(*RetrieveRequest)(nil),       // 7: dht.v1.RetrieveRequest
	(*RetrieveResponse)(nil),      // 8: dht.v1.RetrieveResponse
	(*RemoveRequest)(nil),         // 9: dht.v1.RemoveRequest
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_dht_v1_node_proto_depIdxs = []int32{
	2,  // 0: dht.v1.FindSuccessorRequest.initial:type_name -> dht.v1.Initial
	3,  // 1: dht.v1.FindSuccessorRequest.step:type_name -> dht.v1.Step
	0,  // 2: dht.v1.FindSuccessorResponse.node:type_name -> dht.v1.Node
	0,  // 3: dht.v1.SuccessorList.successors:type_name -> dht.v1.Node
	1,  // 4: dht.v1.DHT.FindSuccessor:input_type -> dht.v1.FindSuccessorRequest
	10, // 5: dht.v1.DHT.GetPredecessor:input_type -> google.protobuf.Empty
	10, // 6: dht.v1.DHT.GetSuccessorList:input_type -> google.protobuf.Empty
	0,  // 7: dht.v1.DHT.Notify:input_type -> dht.v1.Node
	10, // 8: dht.v1.DHT.Ping:input_type -> google.protobuf.Empty
	6,  // 9: dht.v1.DHT.Store:input_type -> dht.v1.StoreRequest
	7,  // 10: dht.v1.DHT.Retrieve:input_type -> dht.v1.RetrieveRequest
	9,  // 11: dht.v1.DHT.Remove:input_type -> dht.v1.RemoveRequest
	4,  // 12: dht.v1.DHT.FindSuccessor:output_type -> dht.v1.FindSuccessorResponse
	0,  // 13: dht.v1.DHT.GetPredecessor:output_type -> dht.v1.Node
	5,  // 14: dht.v1.DHT.GetSuccessorList:output_type -> dht.v1.SuccessorList
	10, // 15: dht.v1.DHT.Notify:output_type -> google.protobuf.Empty
	10, // 16: dht.v1.DHT.Ping:output_type -> google.protobuf.Empty
	10, // 17: dht.v1.DHT.Store:output_type -> google.protobuf.Empty
	8,  // 18: dht.v1.DHT.Retrieve:output_type -> dht.v1.RetrieveResponse
	10, // 19: dht.v1.DHT.Remove:output_type -> google.protobuf.Empty
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_dht_v1_node_proto_init() }
func file_dht_v1_node_proto_init() {
	if File_dht_v1_node_proto != nil {
		return
	}
	file_dht_v1_node_proto_msgTypes[1].OneofWrappers = []any{
		(*FindSuccessorRequest_Initial)(nil),
		(*FindSuccessorRequest_Step)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dht_v1_node_proto_rawDesc), len(file_dht_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dht_v1_node_proto_goTypes,
		DependencyIndexes: file_dht_v1_node_proto_depIdxs,
		MessageInfos:      file_dht_v1_node_proto_msgTypes,
	}.Build()
	File_dht_v1_node_proto = out.File
	file_dht_v1_node_proto_goTypes = nil
	file_dht_v1_node_proto_depIdxs = nil
}
