logger:
  active: true            # Enable or disable logging (true | false)
  level: "info"            # Minimum log level: debug | info | warn | error
  encoding: "console"      # Log output format: console (human-readable) | json
  mode: "stdout"           # Log destination: stdout | file
  file:
    path: ""   # Path to the log file
    maxSize:               # Maximum size (in MB) per log file before rotation
    maxBackups:            # Number of rotated log files to retain
    maxAge:               # Maximum age (in days) to retain old log files
    compress:          # Compress old log files when rotating

simulation:
  duration: 20m            # Total simulation runtime (wall-clock time)

dht:
  idBits: 64               # Identifier space size (keyspace = 2^idBits)

bootstrap:
  mode: "docker"              # Bootstrap mode: docker | route53

  route53:
    hostedZoneId: ""          # AWS Route53 hosted zone ID
    domainSuffix: ""          # Domain suffix for SRV records (e.g., "koorde.dht")
    ttl:                      # TTL for SRV records (in seconds)
    region: ""                # AWS region for Route53 queries (e.g., "us-east-1")

  docker:
    containerSuffix: "koorde-node"  # Docker container name or ID to bootstrap from
    network: ""               # Docker network to connect to
    port:                   # Port on which the KoordeDHT node is listening

csv:
  enabled:             # Enable CSV result logging
  path: ""  # Output file for query results

query:
  rate:                   # Average number of queries per second (global)
  timeout:                # Timeout for each query (e.g., 10s, 1m)
  parallelism:             # Number of concurrent query workers
    min:                   # Minimum number of parallel workers
    max:                   # Maximum number of parallel workers